### ISSUE TITLE
Error Downloading viewxl in RStudio

### ISSUE THREAD

**Issue by WickM** [dreamRs/viewxl#1]
I get the following Error Message when it Try to install your viewxl RStudio Addin
Downloading GitHub repo dreamRs/viewinexcel@master
**Error during wrapup: cannot open URL 'https://api.github.com/repos/dreamRs/viewinexcel/zipball/master'**
It seems that the link https://api.github.com/repos/dreamRs/viewinexcel/zipball/master doesn't exist 
or cant't be found

**Comment by pvictor** [comment]
Hello,
Sorry about that, there was an error in the link, try : 

```r
source("https://install-github.me/dreamRs/viewxl")

# or
devtools::installl_github("dreamRs/viewxl")
```

Victor

**Comment by WickM** [comment]
Yes this seems to work 
devtools::install_github("dreamRs/viewxl")
Thank you
